### ISSUE TITLE
Request to claim name

### ISSUE THREAD

**Issue by ooade** [jackmoore/react-img#1]
Can you please transfer the name of this repository to me? It really seem nice. I'd love to use it for [pimg](https://github.com/ooade/pimg). Thanks a lot 💪

**Comment by jackmoore** [comment]
I'm no longer the NPM owner, it was transferred to @tannerlinsley a year ago or so. You might want to ask him if he still plans on using it.

**Comment by ooade** [comment]
Oh! Thanks a lot @jackmoore 
@tannerlinsley what do you feel? :sweat_smile:

**Comment by tannerlinsley** [comment]
We still intend to use the namespace for a component we're developing in
conjunction with GraphCMS

**Comment by ooade** [comment]
Okay @tannerlinsley 💪
